name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-5-minutes:
    runs-on: ubuntu-latest
    steps:
      - name: Run for 5 minutes
        run: sleep 300
      - name: Pass
        run: echo "Build passed" && exit 0
